cart/urls.py
from django.urls import path, re_path
from .views import add_product, remove_product, decrement_product, clear_cart, cart_total_amount

app_name = "cart"

urlpatterns = [
    path('add_product/<int:product_id>/', add_product, name='add_product'),
    path('remove_product/<int:product_id>/', remove_product, name='remove_product'),
    path('decrement_product/<int:product_id>/', decrement_product, name='decrement_product'),
    path('clear/', clear_cart, name='clear_cart'),
    path('', cart_total_amount, name='cart_total_amount'),

]

web/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    # Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    path('cart/', include('cart.urls')),
    path('orders/', include('orders.urls')),
    # Paths de profiles
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webfrukty/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    # Paths de Auth
    path('accounts/', include('django.contrib.auth.urls')),
    path('accounts/', include('registration.urls')),
    # Paths de profiles
]

if settings.DEBUG:
    from django.conf.urls.static import static
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/models.py
from django.db import models

# Create your models here.

cart/views.py
from django.shortcuts import redirect
from registration.models import Producto
from django.contrib.auth.decorators import login_required
from .cart import Cart
from django.views.generic.base import TemplateView

@login_required(login_url="/accounts/login")
def add_product(request, product_id):
    cart = Cart(request)
    product = Producto.objects.get(id_producto=product_id)
    cart.add(product=product)
    return redirect("listado_productos")


@login_required(login_url="/accounts/login")
def remove_product(request, product_id):
    cart = Cart(request)
    product = Producto.objects.get(id_producto=product_id)
    cart.remove(product)
    return redirect("listado_productos")


@login_required(login_url="/accounts/login")
def decrement_product(request, product_id):
    cart = Cart(request)
    product = Producto.objects.get(id_producto=product_id)
    cart.decrement(product=product)
    return redirect("listado_productos")


@login_required(login_url="/accounts/login")
def clear_cart(request):
    cart = Cart(request)
    cart.clear()
    return redirect("listado_productos")

@login_required(login_url="/accounts/login")
def cart_total_amount(request):
    total = 0.0
    if request.user.is_authenticated:
        for key, value in request.session['cart'].items():
            total = total + (float(value['price']) * value['quantity'])
    return {'cart_total_amount': total}

cart/templates/cart/confirmacion.html
{% extends 'core/base.html' %}
{% load static %}
{% load cart_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}Confirmar Pedido{% endblock %}
</head>
{% block content %}
<body>
    <table class="table">
        <thead class="thead-dark">
          <tr>
            <th scope="col">Producto</th>
            <th scope="col">Cantidad</th>
            <th scope="col">Agregar/Quitar</th>
          </tr>
        </thead>
        <tbody>
            {% if request.session.cart.items %}
                {% for key, value in request.session.cart.items %}
                <tr>
                    <td>{{ value.name }}</td>
                    <td>{{ value.quantity }}</td>
                    <td>
                        <a href="{% url 'cart:add_product' value.product_id %}" class="btn btn-sm btn-success"> + </a>
                        <a href="{% url 'cart:decrement_product' value.product_id %}" class="ml-2 btn-sm btn btn-danger"> - </a>
                        {% load mathfilters %}
                        Total:$ {{value.price|mul:value.quantity}}
                    </td>
                </tr>
                {% endfor %}
            {% else %}
                <tr>
                    <td colspan="3">
                        <div class="alert alert-danger text-center">
                            No tienes productos en el carrito
                        </div>
                    </td>
                </tr>
            {% endif %}
        </tbody>
        <tfoot>
            <tr>
                <td colspan="3">
                    Total: $ {{ cart_total }}
                </td>
            </tr>
            {% if request.session.cart.items %}
                <tr>
                    <td colspan="3">
                        <a href="{% url 'process_order' %}" class="btn btn-success">Crear pedido</a>
                    </td>
                </tr>
            {% endif %}
        </tfoot>
    </table>
      
</body>
</html>